### ISSUE TITLE
Drop Coffeescript/Lodash/Async

### ISSUE THREAD

**Issue by dustinblackman** [dustinblackman/Championify#143]
- [x] Drop Coffescript for ES6/Babel
- [x] Drop Async for Bluebird
- [x] Drop Lodash for Ramda

**Comment by miraage** [comment]
I doubt about dropping `lodash` worthiness. It fits very well into `nodejs`/`npm` because you can simply load only modules you needed.
Not quite sure you'll win a lot with `ramda` unless you need curry a lot.
Also `lodash` is easier to support when new contributors are joined since it is well known library.

**Comment by dustinblackman** [comment]
I curry a lot. ;)
