### ISSUE TITLE
Donation Method

### ISSUE THREAD

**Issue by v1n2e7t** [dustinblackman/Championify#151]
Im not a fan of the service you use for donations. I would add a paypal or coinbase donation option to make it easier

**Comment by dustinblackman** [comment]
Paypal doesn't protect users like me from chargebacks (been through it), and I don't believe the larger population of the League community uses bitcoin. I'm down for any other suggestions you may have though.

**Comment by iggyvolz** [comment]
BountySource accepts paypal...

**Comment by jc4p** [comment]
Dustin,

I would easily do a one time donation (hopefully more than one time but you get the point) via Stripe. If you use Stripe Checkout you could have it run in the app and it enable Bitcoin too, if you'd like.

I agree with you that PayPal is awful at randomly taking your money away from you, and I agree that the larger population of League doesn't use bitcoin, but maybe the smaller population of the League community that downloads an app from GitHub to do item sets might :)

**Comment by dustinblackman** [comment]
@jc4p Thanks! I'll take a closer look in to Stripe this week. :)

**Comment by dustinblackman** [comment]
@jc4p While Stripe does look great, and you're right it would be pretty awesome to have it directly in the app, it doesn't seem to have an option to set the amount of a donation. Like paypal, Stripes dispute process final decision is still by the donars bank, not Stripe, and still include quite a large fee for the dispute ($15) if I were to lose. 

I've previously done donations with Paypal, and because of issues like this I've ended up spending my own money to bring my balances back to 0. For a small project, I really don't want to go through all of that again.

**Comment by ahng1996** [comment]
HI Dustin,

Have you considered looking at Venmo? It seems like it's what you are looking for.

**Comment by dustinblackman** [comment]
Fixed in 2.0.0
