### ISSUE TITLE
Add probuilds.net

### ISSUE THREAD

**Issue by dustinblackman** [dustinblackman/Championify#162]

**Comment by dustinblackman** [comment]
I'm a bit lost of what information people would find useful in this. I've had probuilds requested many times but am I just to bring in the last played items? Show the most popular?

**Comment by Nefari0uss** [comment]
I'm not entirely sure myself. I think you could just scrape the 6 most popular items along with the most popular boots. However, one of the big selling points of probuildes (IMO) is that it shows you the order in which items were built. However, this is something that is more difficult to showcase for several reasons

For starters, you don't know which lane the champion was in. With the ever increasing amount of flex picks, it's very important to figure out who goes where. If a team has Naut, Graves, and Trundle, who is going where? The items built will be different.

Secondly, it's very much dependent on the player shown. Look at Graves. The three player this week with completed item builds are Kirei, Spirit, and Dardoch. Each of them got a different jungle item. This is very context dependent due to the play style of the player and the team that they had. Also, the item path would change based on how your team is doing.

Personally, I don't think probuilds is that useful because it's too context dependent. There's not a large enough data set with aggregated info to make it worth using - especially for something like championify. If probuilds did something where it kept track of a player over a long period of time and gave all the champions he played with data on item builds and such, then it would be more helpful (and also less helpful ~ think about how many pros there are). Just my thoughts.

**Comment by LuaTenshi** [comment]
I would really love some probuilds to be added to this. Even if it's context based it would still be nice to be able to quickly see what popular items are on the champion you're playing. You can also attempt to assume what lane they went based on the team comp.

Show most popular items, and most recent highest KDR final build.

I will probably be able to code something for this in javascript/nodejs/python/php (maybe). But sadly I don't recognize the structure you're using.

**Comment by dustinblackman** [comment]
@LuaTenshi If people feel just the popular items would be useful, then I'll gladly implement it. :)

**Comment by LuaTenshi** [comment]
How about showing the most recent highest KDR final build as well?

I (mostly) made a script that will do the above as well as get the most popular items. The only problem is that it doesn't really output stuff in the correct LoL build format so it's not a simple copy+paste or download into folder thing. That and it uses JQuery because plain Javascript is painful.

**Comment by dustinblackman** [comment]
I've already integrated [probuilds](https://github.com/dustinblackman/Championify/commit/3106738f38517a9b2219cd68e7bbfd8c2cd4b56f) and it'll be out in the next release. I can look into adding KDR too.

**Comment by Firefoxin** [comment]
Hi, Currently for probuilds.net the program show this:
1) Popular Items ----> (Core Items)
2) Popular Boots ----> (Boots)
3) KDA               ----> (Top KDA Items)

because the most important data on probuilds.net web site is **Recent Final Builds** for every champion,
my suggestion is:

1) show 6 **Recent Final Builds** because this is the most important data and builds that any player could have from this site.

2) calculating KDA from **Live Feed** section of the web site, isn't the best method because sometimes game take only 10/15 min and program select 2/0/3 compare to 5/2/5. I think its better to
A) select best KDA from **Recent Final Builds**
B) select another calculation method for KDA from live feed
C) completely remove KDA and change it with **Recent Final Builds**

Thanks, You are the BEST 💯 🥇

**Comment by dustinblackman** [comment]
@Firefoxin Feel free to open a new issue for better tracking.
