### ISSUE TITLE
Allow use of previous versions without mandatory updates

### ISSUE THREAD

**Issue by fuckyourselfup** [dustinblackman/Championify#267]
Sometimes we don't have permission to modify programs in $PROGRAMFILES in order to update, or simply we don't want to update as there are people who don't suffer 'versionitis' and instead would like to use old but stable versions instead of the latest unstable branch.

Whatever... the user should not be compeled to update over and over again to be able to use the program if it is not under his or her desire. But this should be also limited to a certain: the point that the prior version is unable to work properly, in which case the update should be mandatory. If the prior version work as well, it should not be banned from working.

**Comment by dustinblackman** [comment]
Most, if not all my releases recently are to prevent issues with the application itself or League itself. Mandatory updates there to prevent issues that could be caused within the game itself. Past experiences for example is Riot made a change the made the entire ingame store break due to how Championify was formatting item sets. After that, I've made them mandatory.

If you wish to disable them, build from source.
