### ISSUE TITLE
List counter champions

### ISSUE THREAD

**Issue by guykisel** [dustinblackman/Championify#61]
If you can find room for the text somewhere, it would be nice to see something like `Counters: <champ>, <champ>, ...` and `Countered by: <champ>, <champ>, ...` to give you a vague idea about whether you should be playing extra carefully.

**Comment by MiguelAngelDiaz** [comment]
I don't agree. You saturate the app with features it's not meant to handle, and I don't think this app was ever aimed for being more than a convenient "best builds in item sets downloader" app.

My personal opinion.

**Comment by nilesr** [comment]
I'm with Miguel on this one, there's enough text as is. Also, the advice would have to be VERY specific, like just because Riven counters Vlad doesn't tell you that you should play recklessly when playing Riven, you still need to ward, CS well, etc.. but much more specifically you need to sit on Vlad's face and auto + spam spells whenever he's not under turret range. That's a lot of text to include in an item set, and that's just one of an impossibly large set of matchups.

**Comment by guykisel** [comment]
That's fair. If nobody else thinks this is a good idea I don't mind closing it :smile_cat:

**Comment by dustinblackman** [comment]
If Riot ever gives the ability in the UI to better place things than just in text, I'll for sure add this! Until then though I'd rather not overcrowd things. Thanks!
